# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Describing Archives: A Content Standard"
subtitle: "Version 2019.0.4.1"
pdf-link: "https://files.archivists.org/pubs/DACS_2019.0.3_Version.pdf"
pdf-version: "PDF Version 2019.0.3"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Describing Archives: A Content Standard (DACS) is an output-neutral set of rules for 
  describing archives, personal papers, and manuscript collections, and can be applied 
  to all material types. It is the U.S. implementation of international standards (i.e., 
  ISAD[G] and ISAAR[CPF]) for the description of archival materials and their creators.
#baseurl: "/static/dacs" # the subpath of your site, e.g. /blog
baseurl: ""
url: "https://saa-ts-dacs.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: ts_dacs
github_username:  ts_dacs
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ts_dacs"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saa-ts-dacs"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Build settings
markdown: kramdown
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.18.1"
minimal_mistakes_skin    : "air" # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "single"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
